name: padel_app
description: "Padel MVP application"
publish_to: 'none'
version: 1.0.0+1
author: "Andrii Kosiak"

# АВТОРСКОЕ ПРАВО
# Copyright © 2026 Andrii Kosiak. All rights reserved.
# Unauthorized copying, modification, or redistribution is strictly prohibited.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # База данных и авторизация
  supabase_flutter: ^2.8.0
  
  # Биометрия и вход
  local_auth: ^2.3.0
  sign_in_with_apple: ^6.1.0
  
  # UI и графики
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

  # Настройки Flutter (строго один раз!)
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # Чтобы добавить картинки, раскомментируй и напиши так:
  assets:
    - assets/logo.png
  # --- БЛОК НАСТРОЙКИ ИКОНОК  
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
    